feat: add directors
AlexandraKozhevnikova/java-filmorate pull request #10
Opened 2022-12-05 12:51 UTC by GeorgyMalkhozov

2022-12-05 17:19 UTC, AlexandraKozhevnikova requested changes

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +public class Director implements IdControl {
Не уверена что  Director нужен интерфейс этот.. Для чего?

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.director = Objects.requireNonNullElse(director, Collections.emptyList());
элегантно выглядит)

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.forEach(film -> film.setDirector(
вот тут возможно поправит Ромин комит с рефакторингом получения фильмов

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.warn("Wrong type of sort declared");
а вот где ты отбиваешь ошибку) клево что оброботал такой кейс

Но все равно голосую за енам

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.warn("Wrong type of sort declared");
Предлагаю в лог добавить само значение sortTypeForDirector ( а то как потом узнать чего туда передавали)

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NoSuchElementException("Wrong type of sort declared");
ИМХО, тут не подойдет NoSuchElementException, так как
-NoSuchElementException обрабатывается как ошбика логики ( см ru.yandex.practicum.filmorate.exception.ErrorHandler#handleNoSuchElementException)
-  NoSuchElementException подходит когда мы в бд не нашли сущность по id

тут же валидационная ошибка, так как передан не ожидаемый тип сортировки
 с ходу какое исключение кидать не скажу, если сам не найдешь, можем вместе подумать

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/DirectorController.java
> +public class DirectorController {
Лайк) очень читабельный и понятный контроллер)

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
> +            @RequestParam(name = "sortBy", defaultValue = "year")
судя по коду параметр сортировки обязаетельный да? 
(не может быть не передан?)

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/director/UpdateDirectorRequest.java
> +    @NotBlank(message = "'name' should non be empty")
спасибо за указание месаджа)

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/mapper/DirectorMapper.java
> +                .name("")
тут помню твои пояснения, но предложить нечего((

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/resources/sql/schema.sql
> +                                       PRIMARY KEY,
судя по отступам сьехало форматирование?

2022-12-05 17:19 UTC, AlexandraKozhevnikova commented on src/main/resources/sql/schema.sql
> +                                       PRIMARY KEY,
PRIMARY KEY наверно можно оставить на предыдущей строке

2022-12-05 18:39 UTC, AlexandraKozhevnikova commented
И главное, ПР должен быть в ветку develop! (сейчас в main)

в ветку мейн мы вмержим ветку девелоп, когда все фичи будут готовы для сдачи заказчику

2022-12-06 14:41 UTC, GeorgyMalkhozov commented on src/test/java/ru/yandex/practicum/filmorate/componentTest/DirectorsTest.java
> +
пофиксил

2022-12-06 14:41 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
пофиксил

2022-12-06 14:42 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/DirectorDaoImpL.java
> +     Returns new film Id which be generated by database
пофиксил

2022-12-06 14:43 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/DirectorDaoImpL.java
> +        List<Director> list = new ArrayList<>();
поменял задумку в процессе реализации и забыл удалить потом) пофиксил сейчас

2022-12-06 14:49 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/DirectorDaoImpL.java
> +    private Director mapRowToDirector(ResultSet resultSet, int rowNum) throws SQLException {
перенес

2022-12-06 14:51 UTC, RomanPolyansky requested changes

2022-12-06 14:51 UTC, RomanPolyansky commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +                        (sortCodeForDirectorMovies.equals("likes") ?
в сервсе есть отбивка

2022-12-06 14:51 UTC, RomanPolyansky commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.director = Objects.requireNonNullElse(director, Collections.emptyList());
style: director**S**

2022-12-06 14:51 UTC, RomanPolyansky commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NoSuchElementException("Wrong type of sort declared");
я думаю это NotImplementedException ?

2022-12-06 14:51 UTC, RomanPolyansky commented
Согласен с комментами Саши, и надо внести правки с апдейта на develop

2022-12-06 14:56 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/DirectorDaoImpL.java
> +                "LEFT JOIN director D ON FD.DIRECTOR_ID = D.DIRECTOR_ID " +
ну тут вопрос вкуса скорее - результат по факту один и тот же и у LEFT и у INNER. Просто по опыту стараюсь использовать LEFT там где он применим

2022-12-06 14:56 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +                        (sortCodeForDirectorMovies.equals("likes") ?
думал про enum) ок, добавляю сейчас

2022-12-06 17:51 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +                        "SELECT F.id, F.name, F.description, F.release_date, F.duration, F.rating_MPA " +
это копипаста из методов выше - getfilteredfilm, getfilmid) ок, поправлю во всем классе

2022-12-06 17:58 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +                                    "SELECT DISTINCT film_id, " +
но для этого нужно поменять диалект SQL - текущий не дает пользоваться DECLARE

2022-12-06 17:59 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +public class Director implements IdControl {
как и фильму - делать сет и гет айди

2022-12-06 18:00 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.director = Objects.requireNonNullElse(director, Collections.emptyList());
пофиксил

2022-12-06 18:01 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.forEach(film -> film.setDirector(
да, уже переделал с учетом этого комита

2022-12-07 09:37 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +                                    "SELECT DISTINCT film_id, " +
в итоге сделал по-другому: jdbc делаем дефолтную сортировку по лайкам, а в сторадже (если через контроллер приходит year) сортируем стримом по году

2022-12-07 10:29 UTC, closed without merging

2022-12-07 12:24 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/DirectorDaoImpL.java
> +                "LEFT JOIN director D ON FD.DIRECTOR_ID = D.DIRECTOR_ID " +
спасибо)