Add remove endpoint
AlexandraKozhevnikova/java-filmorate pull request #15
Opened 2022-12-06 18:41 UTC by TheRathustra

Добавил методы для удаления фильмов и пользователей

2022-12-07 10:41 UTC, AlexandraKozhevnikova requested changes
ПР должен быть в ветку develop))

2022-12-07 18:50 UTC, AlexandraKozhevnikova requested changes
Хороший ПР получился - небольшой и читаемый

Нужны юнит тесты хотябы  по два на сущность, удалить существующий и удалить несуществующий

Хочешь добавляй сюда, хочешь этот заапрувим и вольем, а тесты в отдельной ветке можно добросить (но тогда заводи задачу в джиру, асайни на себя  - чтобы не забыли)

2022-12-07 18:50 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/UserDaoImpl.java
> +        String sql = "DELETE FROM user_filmorate WHERE id=?";
по форматированию поправь плиз  для единообразия пробелы вокруг знака равенства`"id = ?"`

2022-12-07 18:50 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.deleteUser(userId);
По валидациям не вижу обработки что прислали userId не валдиный или которого не существует
НО видимо раз тесты в Постмане проходят то все ок
Но если просто забыл обработать кейс - добавь плиз

2022-12-07 19:09 UTC, RomanPolyansky requested changes
Всё гуд, но нужен хотя бы один тест!)

2022-12-09 20:53 UTC, AlexandraKozhevnikova approved these changes
Поставила лайк, там есть пара мелочей
чекни плиз

и fyi без подлития свежего девелопа и резолва конфликтов не получится вмержить

2022-12-09 20:53 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/web/controller/UserControllerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Просьба отказаться от иморта звездочками (в настройках идее)

2022-12-09 20:53 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/web/controller/UserControllerTest.java
> +    void deleteUser() {
Есть тесты на удаление существующего юзера

Нет теста на удаление несуществующего, добавь плиз

2022-12-09 20:53 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/web/controller/FilmControllerTest.java
> +        Film newFilm = new Film(0, "Test", "Test", LocalDate.now(), 1, 1, genreList);
а то что тут присваивается id 0 нечего не ломает? В БД поле автогенерится...

2022-12-09 20:53 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/web/controller/FilmControllerTest.java
> +        try {
может тут ловить более стандартными способами исключение
например как в тесте ru.yandex.practicum.filmorate.InMemoryUserServiceTest#updateNotExistUserTest

2022-12-09 20:53 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/web/controller/UserControllerTest.java
> +@Sql({"classpath:sql/schema.sql"})
а что дает эта аннотация? Я так понимаю спринг по дефолту видит этот файл

2022-12-10 11:54 UTC, RomanPolyansky approved these changes

2022-12-11 08:43 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/web/controller/UserControllerTest.java
> +    void deleteUser() {
судя по всему 
@Test
    void deleteNotExistFilm() {
        service.deleteFilm(-345);
       
    }

такой тест проходит и нет отбивки на несуществующего юзера

2022-12-11 08:44 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/web/controller/FilmControllerTest.java
> +        try {
Для фильма исправила, для Юзера оставила

2022-12-11 09:04 UTC, merged