"feat: Добавить функциональность 'Отзывы'"
AlexandraKozhevnikova/java-filmorate pull request #18
Opened 2022-12-07 21:50 UTC by StasNL

2022-12-08 14:44 UTC, AlexandraKozhevnikova commented
Стас обрати внимание я поменяла целевую ветку на девелоп (было в меин)

2022-12-08 15:41 UTC, AlexandraKozhevnikova requested changes
Стас у тебя очень большая задача) Удивляюсь как ты справился с ней так быстро
Очень тяжело ревьюить так много материала за раз, очередной раз топлю за небольшие ПР

По замечаниям - накидала что заметила, если что-то не понятно или не согласен: давай обсуждать чатом или в зум

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewDaoImpl.java
> +        if (filmId == null) {
Клевое решение) не знаю что скажет ревьюер но это читаемая и понятная логика

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewDaoImpl.java
> +        if (filmId == null) {
теперь поняла почему ты там в интерфейсе написал именно Integer а не примитив)
и даже вспомнила мы это вроде в чате обсуждали) сорян забыла)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewDaoImpl.java
> +
мне кажется тут лучше без пустой строки , но на твое усмотрение

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +    public Integer getUsefulByReviewId(int reviewId) {
а вот тут уже кажется можно возвращать примитив, верно?

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +        String sql = "SELECT SUM(USEFUL) FROM REVIEW_USEFUL WHERE REVIEW_ID = ?";
и тут и дальше кодстаил скл

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +     * значит это лайк, если отрицательное (должно быть -1), значит дизлайк.
спасибо за пояснения))

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +        checkReactionType(reviewId, userId);
здорово что добавил проверку на существование лайка)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +        jdbcTemplate.update(sql, reviewId, userId, -1);
такие  литералы принято считать магическими так как не понятно откуда они беруться

поэтому принято вынести значение в константу наверх класса и коментами дописать почему именно (-1) так как те разработчики, что не в контексте задачи не могут догадаться что имеется в виду

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +     * значит это лайк, если отрицательное (должно быть -1), значит дизлайк.
но к какому оно методу?

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +        return Map.of("logic error", e.getMessage());
у меня тут вопрос:

в моем мире: 
400 - это плохой запрос, ошибки валидации
404 - хороший запрос но такого объекта у нас нет - ошибка логики

тут вижу
"logic error" и HttpStatus.BAD_REQUEST

Что тут все-таки имеется ввиду, что пользователь ввел ерунду или что просто мы не нашли такой отзыв?

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +import lombok.*;
Как уже писала в других ПР , очень не рекомендуется звездочки в недомашних проектах - последствия это конфликты имен

(настраивается и идее)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NotNull(message = "'userId' must not be null")
спасибо за месседжи)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public boolean getIsPositive() {
почему решил этот геттер отдельно написать, если юзаешь ломбок анотацию?
мож хотел добавить кастомную логику сюда?

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public ReviewService(@Qualifier("dbReviewStorage") ReviewStorage reviewStorage, UserService userService, FilmService filmService) {
тут тоже остается вопрос зачем @Qualifier("dbReviewStorage")?

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        filmService.getFilmById(filmId);
Получение  фильма  через filmService.getFilmById(filmId) - очень жирный запрос, так как по-мимо проверки что такоей фильм есть , метод идет в таблицу Жанров, потом в Режиссеров и дообогащает Фильм этими данными

просто для проверки рекломендую использовать метод:
ru.yandex.practicum.filmorate.db.DbFilmStorage#isExist

пример использования есть в методе обновления фильма


пс для Юзера все ок( там колько один метод)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        filmService.getFilmById(filmId);
и так как этот метод используется всего один раз, может я бы не стала выносить в отдельный (хотя опять же смотрится неплохо но противоречит одни метод - одна функция, но тут может спорный вопрос)

мне кажется можно в самом методе сделать так 
```
public Review add(Review review) {
        userService.getUserById(userId);
filmService.isExist() // DbFilmStorage#isExist (  тут тогда нужно будет этот метод в сервис прокинуть)
        int id = reviewStorage.add(review);
        return getReviewById(id);
    }

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +
пустая строка и видимо сьехало форматирование -нет пустых строк между методами

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/ReviewController.java
> +            @RequestParam(name = "count", defaultValue = "10") Integer count
Гуд)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/review/AddReviewRequest.java
> +    @JsonGetter
расскажешь что это означает?

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/main/resources/sql/schema.sql
> +(
вот это форматирование нужно настроить в идее, чтобы скобка на новую строку не переезжала по хоткею автоформатирования


предлагаю придерживатья форматированию который был предложен в тренажере - скобка на первой строке

```
CREATE TABLE films (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title varchar(40) NOT NULL,
        produced integer NOT NULL,
        date_prod date,
        kind varchar(10),
        len_min integer
);

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/ReviewServiceTest.java
> +    @BeforeEach
Метод      @BeforeEach принято писать в начале класса перед тестами (опять же для читаемости)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/ReviewServiceTest.java
> +    private Review reviewCreation() {
приватные методы всегда в самом конце файла, после всех публичных

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/ReviewServiceTest.java
> +    @AfterEach
этот метод после последнего тестового метода)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/ReviewServiceTest.java
> +    public void clearDb() {
идут жаркие споры, но на лету чистить общую БД не нужно, давай найдем другие пути (можно по зуму созвонится)

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/ReviewServiceTest.java
> +    final JdbcTemplate jdbcTemplate;
вдимо эта иньекция в тестовом классе не пригодится

2022-12-08 15:41 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/ReviewServiceTest.java
> +        reviewService.like(1, 1);
лучше разбить на два теста, чтобы тесты были атомарными:
1) удаление несуществующего лайка
2) успешное удаление существующего лайка

2022-12-08 15:43 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewDao.java
> +    List<Review> getReviewsByFilmId(Integer filmId);
отмена) дальше по коду увидела )

2022-12-08 19:31 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/DbReviewStorage.java
> +@Qualifier("dbReviewStorage")
На самом деле нужды нет. Меня просто в детстве напугали =)
Я не ставил @Autowired над конструкторами, потому что если можно привязать к нему только одну реализацию, Spring сам разберётся. Ревьюер замечание сделал. Вот теперь всё заранее делаю =) Можно убрать.

2022-12-08 19:59 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewDao.java
> +public interface ReviewDao {
Нарисовал. Вроде похоже... Я раньше в другой рисовал, но вроде разобрался =)

`Table review {
  review_id int [pk]
  content varchar(300) [NOT NULL]
  isPositive boolean [NOT NULL]
  user_id int [ref: < user_filmorate.id]
  film_id int [ref: < film.id]
}

Table review_useful {
  review_id int [ref: > review.review_id]
  user_id int [ref: < user_filmorate.id]
  useful int [NOT NULL]
  note: 'pk = review_id + user_id'
}`

2022-12-08 20:45 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbReviewStorage.java
> +@Qualifier("dbReviewStorage")
Я тоже за то чтобы  @Autowired  оставить

2022-12-08 20:48 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewDao.java
> +public interface ReviewDao {
https://dbdiagram.io/d/636256b3c9abfc61116fc913 обновила)

2022-12-08 21:56 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/DbReviewStorage.java
> +@Qualifier("dbReviewStorage")
Ok

2022-12-08 22:22 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewDaoImpl.java
> +        String sql = "UPDATE REVIEW SET CONTENT = ?, ISPOSITIVE = ? " +
Поправил, где нашёл.

2022-12-08 22:28 UTC, StasNL commented on src/test/java/ru/yandex/practicum/filmorate/ReviewServiceTest.java
> +        reviewService.like(1, 1);
У меня тесты по методам разбиты.
Наш наставник сказал, что так делает и мне кажется, что так просто и понятно.
Для того, чтобы никто не путался, оставляю комменты.
Если настаиваете, разобью. Но это будет очень много методов.

2022-12-09 14:01 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +    public Integer getUsefulByReviewId(int reviewId) {
А почему примитив? Обёртки же удобнее.

2022-12-09 14:02 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +     * значит это лайк, если отрицательное (должно быть -1), значит дизлайк.
Это javadoc. Он всегда пишется перед методом, к которому относится.

2022-12-09 14:08 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +        return Map.of("logic error", e.getMessage());
У меня для тебя хорошие новости, другие миры в этом плане от твоего не отличаются...

Конечно пользователь ввёл ерунду. Лайка нет, а он его удаляет. Или лайк есть, а он его снова ставит.

2022-12-09 14:13 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public boolean getIsPositive() {
Так как переменная начинается с is, при обращении через lombok json глючит и в Postman название переменной уходит как просто positive. Это лечится добавлением геттера.

2022-12-09 14:30 UTC, StasNL commented on src/main/resources/sql/schema.sql
> +(
А где эти настройки? Я нажал ctrl alt L и он так сделал

2022-12-09 20:18 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +     * значит это лайк, если отрицательное (должно быть -1), значит дизлайк.
Тут я имею ввиду что в джава док пишется про определение типа реакции, а в методе ниже мы получаем некий  useful и все, то есть я по смыслу не уловила связи

2022-12-09 20:41 UTC, AlexandraKozhevnikova approved these changes
Прошлась по всем коментам, от меня ОК
Там есть мелочи, но ты их уже сам чекни
Ставлю апрув, чтобы ради мелких правок не возвращать на ревью

2022-12-09 20:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +        return Map.of("logic error", e.getMessage());
Если ты согласен что это ошибка валидации
замени плиз
```
        return Map.of("validation error", e.getMessage());

2022-12-09 20:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +import lombok.*;
Ну прям ломбок наверно нет) но так как это общая настройка в идее не зависимо от пакета, то бросается в глаза. Проще сразу отключить настройку, дать привыкнуть глазам к лучшим практикам и не переживать что где-то в другом месте может проскачить, имхо

https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

2022-12-09 20:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public boolean getIsPositive() {
Спасибо, буду знать)

2022-12-09 20:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                    (
что-то со скобками форматирование уехало 
в одну строчку лучше 43 44 и 45 строка

2022-12-09 20:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +    public Integer getUsefulByReviewId(int reviewId) {
прости вижу что внизу метода все равно 0 присваеваешь, а у примитива это по-дефолту

2022-12-09 20:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/review/AddReviewRequest.java
> +    @JsonGetter
понятно)

2022-12-09 20:42 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/ReviewServiceTest.java
> +        reviewService.like(1, 1);
не настаиваю)

2022-12-10 01:13 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +    public Integer getUsefulByReviewId(int reviewId) {
Ок, переделаю.

2022-12-10 01:13 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +        jdbcTemplate.update(sql, reviewId, userId, -1);
Сделано

2022-12-10 01:19 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +     * значит это лайк, если отрицательное (должно быть -1), значит дизлайк.
Переписал

2022-12-10 01:19 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +import lombok.*;
Переделал

2022-12-10 01:20 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public boolean getIsPositive() {
юавелкам =)

2022-12-10 01:21 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        filmService.getFilmById(filmId);
Сделал

2022-12-10 01:21 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +
done

2022-12-10 01:35 UTC, StasNL commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +    public Integer getUsefulByReviewId(int reviewId) {
Переделал, Идея ругается, что может быть нульпоинтэксепшн. Вернул назад

2022-12-10 11:53 UTC, RomanPolyansky approved these changes

2022-12-11 08:48 UTC, merged