Group #4 project  12 sprint
AlexandraKozhevnikova/java-filmorate pull request #24
Opened 2022-12-11 09:12 UTC by AlexandraKozhevnikova

2022-12-11 09:23 UTC, AlexandraKozhevnikova commented
Функциональность Лента еще в процессе - поэтому два теста в Постмане не проходят

2022-12-11 11:04 UTC, Frilock requested changes
Добрый день, смотрите, чтобы корректно проверять работу, в файле Readme должна быть указана функциональность, которую вы реализовали, чего я не увидел. 

Также я оставил несколько комментариев к работе, посмотрите, пожалуйста. 

Сразу оговорюсь, что в работе в ваших SQL запросах не должно быть более двух вложенных подзапросов.
То есть конструкция типа: select .... (select ...) ... (select ...) не допускается, нужно использовать JOIN. 

Также прошу обратить внимание по максимум избегать запросов в БД в цикле, это будет важно на больших объёмах данных и большой нагрузке приложения. То есть постарайтесь по максимуму заменить N единичных запросов на 1 групповой (как пример, у Вас есть N id вы делаете в цикле N запросов findById, затем работаете с сущностью, нужно заменить N findById на один запрос который вернет Вам коллекцию с которой вы будете дальше работать).

Кроме того, предлагаю Вам в IDEA установить plugin sonarlint - статический анализатор кода, который подскажет Вам ряд хороших практик и некоторые места где возможны ошибки.

Жду новую иттерацию.

2022-12-11 17:43 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +    public DbFilmStorage(FilmDao filmDao, FilmGenreDao filmGenreDao, FilmLikeDao filmLikeDao, DirectorDao directorDao, RecommendationsDao recommendationsDao) {
@AlexandraKozhevnikova

2022-12-11 17:43 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
@AlexandraKozhevnikova

2022-12-11 17:44 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +        Optional<Film> film = filmDao.getFilmById(id);
@RomanPolyansky

2022-12-11 17:44 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +                .map(this::getItemById)
@AlexandraKozhevnikova

2022-12-11 17:45 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +        Optional<Director> director = directorDao.getDirectorById(directorId);
@GeorgyMalkhozov

2022-12-11 17:45 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +        if (sortTypeForDirectors.equals(SortTypeDirectors.YEAR)) {
@GeorgyMalkhozov

2022-12-11 17:46 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/DirectorDaoImpL.java
> +    public DirectorDaoImpL(JdbcTemplate jdbcTemplate) {
@GeorgyMalkhozov

2022-12-11 17:46 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/DirectorDaoImpL.java
> +@Slf4j
@GeorgyMalkhozov

2022-12-11 17:46 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +                "WHERE 1=1 " +
@AlexandraKozhevnikova

2022-12-11 17:47 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmLikeDaoImpl.java
> +
@AlexandraKozhevnikova

2022-12-11 17:48 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/RecommendationsDaoImpl.java
> +        SqlRowSet maxCommonUserIdsRs = jdbcTemplate.queryForRowSet(
@RomanPolyansky

2022-12-11 17:48 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/ReviewUsefulDaoImpl.java
> +
@StasNL

2022-12-11 17:49 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
@AlexandraKozhevnikova

2022-12-11 17:49 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        return "success";
@StasNL

2022-12-11 17:50 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<Film> getFilmRecommendations(int user_id) {
@RomanPolyansky

2022-12-11 17:50 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/SearchByType.java
> +    private String apiParam;
@AlexandraKozhevnikova

2022-12-12 13:48 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +        Optional<Director> director = directorDao.getDirectorById(directorId);
исправлено

2022-12-12 13:50 UTC, GeorgyMalkhozov commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +        if (sortTypeForDirectors.equals(SortTypeDirectors.YEAR)) {
исправлено

2022-12-13 12:28 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +    public DbFilmStorage(FilmDao filmDao, FilmGenreDao filmGenreDao, FilmLikeDao filmLikeDao, DirectorDao directorDao, RecommendationsDao recommendationsDao) {
Спасибо, поправила

2022-12-13 12:29 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
Нигде не встречала такие пометки (ни в тренажере ни в ноушене) может пропустила
Добавила

2022-12-13 12:33 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +                .map(this::getItemById)
Если правильно понимаю вопрос, но наверно не сможем
Так как сначала ходим в таблицу лайканых фильмов и получаем например два фильма с сотрировкой по залайконности, а потом идем добывать рандомные фильмы из таблицы фильмов причем такие чтобы не пересекались с первым списком и третьм шагом объединяем

но опять же есть переджнойнить фильмы и лайки (что на реальных бд наверно нереально долго из-за размеров таблиц) то можно напилить другую локику с с помощью джойна и группировки получить сразу фильмы и с лайками и без и с сортировкой

2022-12-13 12:37 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +                "WHERE 1=1 " +
это для легкого и опционального подсоедиения условий, которые могут быть а могут не быть и нужна устойчивая конструкция которая не ломает запрос 
AND не подойдет если с него будет начинаться фильтр и пришлось такую заглушку подсмотреть

```
"WHERE 1=1 " +
                (!excludeList.isEmpty() ? "AND id NOT IN (:ids) " : "") +
                (genreId == null ? " " : " AND id IN (SELECT film_id FROM film_genre WHERE genre_id = :genreId)") +
                (year == null ? " " : " AND  EXTRACT(YEAR FROM release_date) = :year") +
                (title == null ? " " : " AND name ILIKE  :title") +
                (count > 0 ? " LIMIT (:count)" : "");

2022-12-13 12:47 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmLikeDaoImpl.java
> +
на рельсах jbdc не нашла красивого решения, поэтмоу пришлось собрать как смогла
магические значения вынесла в константы
дописала коментов

цель была - гибко фильтровать

2022-12-13 12:48 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
поправила

2022-12-13 14:16 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +                .map(this::getItemById)
Если тут вопрос не про метод, а про способ получения из ид - объекта фильма

то, в целом кажется логично ходить не за одним методом, а сразу за один запрос забрать всю пачку фильмов по из id, но тут сложность встала в том что фильмы мы можем получить из одной таблицы, а потом каждый нужно дообогащать запросом за жантрами и запросом за дирижерами

и сейчас мы это решили тем что любые методы по сути дойдут до 


```

@Override
    public List<Film> getAllItems() {
        List<Film> films = filmDao.getAllFilms();
        for (Film film : films) {
            setFieldsOnFilm(film);
        }
        return films;
    }

    @Override
    public Film getItemById(int id) {
        Film filmFromDb = filmDao.getFilmById(id).orElseThrow(() -> new NoSuchElementException("film with id = " + id + " not found"));
        setFieldsOnFilm(filmFromDb);
        return filmFromDb;
    }



``

  этих методов, а уже эти методы знают какими именно сущностями нужно дообаготить фильм

и тогда уже не понятно можно ли имея ид 1, 2 ,4 например сходить в бд за 1 раз и получить все три фильма с их  жанрами и режиссерами? и нужно ли писать такой запрос. В целом если это верная стратегия и нужно собрать такой запрос - переделаем, но нужно понимать что это то что требуется?

2022-12-14 14:19 UTC, Frilock approved these changes
Добрый день, в целом мне все понравилось, все что просил поправили. Поздравляю с, возможно первым, опытом работы в команде. В работе получилось сделать довольно понятные запросы к базе, а также понравилось, что решили попробовать повозиться с аспектом.

2022-12-14 14:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/RecommendationsDaoImpl.java
> +            if (userFilmIds.contains(id)) commonFilmsIds.add(id);
Просьба обособлять конструкции if и else

2022-12-14 14:54 UTC, merged