ТЗ 10 спринт. Спринг и Рест (work in progress)
AlexandraKozhevnikova/java-filmorate pull request #4
Opened 2022-10-24 21:09 UTC by AlexandraKozhevnikova

добавлены ручки и  di spring

2022-10-24 21:12 UTC, AlexandraKozhevnikova commented
Подскажите пожалуйста где бага 
Ручка getFilms -  отдает и Фильмы и Юзеры (видимо где-то ошибка с дженериками и интерфейсом, но не могу найти) Не нашла материалы про то как дженерики могут имплементировать недженерик интерфейсы

2022-10-25 17:12 UTC, Frilock requested changes
Добрый вечер, написал ряд комментариев к работе. Думаю, что стоит попробовать развести ваши хранилища через Qualifier, либо попробуйте сделать так, как я написал в комментарии. Кроме того, вы же видите какой тест у вас падает в постмане, попробуйте написать unit тест аналогичный, где в debug режиме посмотрите что именно не  так. Заодно приобретёте хороший навык.
Кроме того, с мапперами что то странное, какой то из них является бином, а какой то нет. Почему?

2022-10-25 17:12 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/BadFriendshipException.java
> +    public BadFriendshipException(String s) {
Давайте параметр читаемо назовем, например, message

2022-10-25 17:12 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(){};
Можно NoArgsConsturctor повесить, либо поправить форматирование, как минимум ; в конце не нужно по идее

2022-10-25 17:12 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return name.isBlank() ? login : name;
Вообще советую использовать StringUtils.isBlank - дабы еще проверять что поле != null.

2022-10-25 17:12 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        firstFriend.friends.add(secondFriend.getId());
Мне кажется что логику из этих методов нужно перенести в UserStorage. Тут заинжектить бин UserStorage и у него методы вызывать

2022-10-25 17:12 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private Storage<Film> filmStorage;
Не уверен, что такая штука будет работать. Либо попробуйте через Qualifier сделать. А лучше вообще сделайте интерфейс Storage, а затем реализации UserStorage, FilmStorage и т.д. По идее так точно работать должно.

2022-10-26 20:35 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/mapper/UserMapper.java
> +@Component
видимо просто забыла, добавила бин для второго

2022-10-26 20:39 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/exception/BadFriendshipException.java
> +    public BadFriendshipException(String s) {
done

2022-10-26 20:40 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(){};
При использовании Ломбока на эту строку не попасть при дебаге 🙈

2022-10-26 20:40 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(){};
убрала точку с запятой

2022-10-26 20:41 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return name.isBlank() ? login : name;
name.isBlank() - включает уже проверку на null ( тестила этот код через постман)

2022-10-26 20:43 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return name.isBlank() ? login : name;
из постмана 
`POST /users HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Accept: */*
Content-Length: 81

{
  "login": "dolore",
  
  "email": "test@mail.ru",
  "birthday": "1446-08-20"
}

200 ок

{
    "id": 6,
    "email": "test@mail.ru",
    "login": "dolore",
    "name": "dolore",
    "birthday": "1446-08-20"
}`

2022-10-26 20:46 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        firstFriend.friends.add(secondFriend.getId());
Судя по ТЗ:


стораджи отдельно:
`Создайте интерфейсы FilmStorage и UserStorage, в которых будут определены методы добавления, удаления и модификации объектов`

сервисы отдельно:
`
Создайте UserService, который будет отвечать за такие операции с пользователями, как добавление в друзья, удаление из друзей, вывод списка общих друзей. Пока пользователям не надо одобрять заявки в друзья — добавляем сразу. То есть если Лена стала другом Саши, то это значит, что Саша теперь друг Лены.`


или я не правильно поняла суть замечания🤓

2022-10-26 20:47 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private Storage<Film> filmStorage;
да, тут не сработало. Подсказали вариант сделать наследников от дженерик-классов. Взлетело) перевесила бины и интерфейсы теперь как по ТЗ

2022-10-27 15:26 UTC, Frilock requested changes
Добрый день, пару небольших комментариев

2022-10-27 15:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return name.isBlank() ? login : name;
Вы в unit тесте попробуйте 
String name = null;
println(name.isBlank());

2022-10-27 15:26 UTC, Frilock commented on README.md
> +1) Не могу понять где баг, судя по тестам постмана перемешиваются где-то Фильмы и Юзеры. Буду благодарна если укажите проблему
Можно убирать я считаю)

2022-10-27 15:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparingInt(it -> (-1) * it.getValue().size()))
Я так понимаю умножение на -1 для того, чтобы в обратном порядке сортировать? Так там вроде есть .reverse() или что то такое

2022-10-27 15:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        firstFriend.friends.add(secondFriend.getId());
Тут как минимум обращение к полю нужно сделать через get. То есть поля коллекции в классе User надо приватным сделать как и все остальные поля =)

2022-10-28 11:20 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return name.isBlank() ? login : name;
Поняля, падает с  NPE) поправила

2022-10-28 11:40 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        firstFriend.friends.add(secondFriend.getId());
поправила

2022-10-28 11:45 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return name.isBlank() ? login : name;
видимо для   String  дефолт не   null  a  пустая строка

2022-10-28 12:47 UTC, Frilock approved these changes
Александра, молодец, работа принята.

2022-10-28 15:23 UTC, merged