Add database
AlexandraKozhevnikova/java-filmorate pull request #6
Opened 2022-11-24 20:46 UTC by AlexandraKozhevnikova

ТЗ 11 спринта
сделано хранилище данных на h2

2022-11-25 17:35 UTC, Frilock requested changes
Добрый вечер, интересная работа, использовано много вещей, которых я не видел у Ваших коллег, например, проверки на БД и NamedParameterJdbcTemplate. Написал довольно много комментариев, но в целом они не очень большие. Из основного, я бы посоветовал отказаться от NamedParameterJdbcTemplate - достаточно стандартного JdbcTemplate. Нужно изменить логгирование на Slf4j. Поправить наименования таблиц. А так же хотелось бы по больше негативных тестов

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/user/AddUserRequest.java
> +package ru.yandex.practicum.filmorate.web.dto.user;
Мне вообще кажется что вы зря добавили общий пакет web, хотя конечно дело ваше.

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/web/mapper/FilmMapper.java
> +@Log4j2
Лишняя аннотация?

2022-11-25 17:35 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/UserServiceTest.java
> +    UserStorage storage = new InMemoryUserStorage();
Модификаторы

2022-11-25 17:35 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/ImMemoryFilmStorageTest.java
> +    FilmStorage storage = new InMemoryFilmStorage();
Модификатор

2022-11-25 17:35 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/ImMemoryFilmStorageTest.java
> +    public void updateFilmTest() {
Хочется еще увидеть негативные тесты с использованием assertThrows

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/Id.java
> +public class Id {
А зачем этот класс?

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/MpaController.java
> +    @GetMapping()
() пустые скобки лучше убрать

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDao.java
> +    int insertFilm(Film film);
А что за число возвращаемое?  Как то не очевидно...

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +            film = null;
Можно сразу Optional.empty, а в try - return ...

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +        String sql = "SELECT id, name, description, release_date, duration, rating_MPA FROM film WHERE id = ?";
А почему параметры перечисляете а не через *?

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +        List<Film> films = namedDb.query(
В 1 строчку кажется влазит

2022-11-25 17:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +    private NamedParameterJdbcTemplate namedDb;
Вообще интересное решение, я у ваших коллег таких реализаций не видел. Вообще если интересно то достаточно было бы JdbcTemplate  использовать и все. Можете поразбераться, сейчас чуток лишней работы делаете

2022-11-25 17:52 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +    private NamedParameterJdbcTemplate namedDb;
Если честно я просто не нашла рабочий вариант на обычном jdbc. Поэтому пришлось изгаляться.

2022-11-25 17:56 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +    private NamedParameterJdbcTemplate namedDb;
Я думаю остальные просто джойнили фильмы и лайки. Но я подумала что это ту мач для реального приложения

2022-11-25 18:01 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +    private NamedParameterJdbcTemplate namedDb;
В интернете нашла только такие способы из статьи https://www.baeldung.com/spring-jdbctemplate-in-list 

первый способ не заработал и он деприкейтид, а второй это тот что я сделала

2022-11-25 18:02 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +    private NamedParameterJdbcTemplate namedDb;
В связи с вышесказанным) прошу показать на какой способ предлагается исправить код

2022-11-27 20:10 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/mapper/UserMapper.java
> +@Component
убрала

2022-11-27 20:16 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/DbFilmStorage.java
> +    public DbFilmStorage(FilmDao filmDao, FilmGenreDao filmGenreDao, FilmLikeDao filmLikeDao) {
да помню, но пока не привыкла к спрингу пишу эти штуки явно чтобы не путаться

2022-11-27 20:17 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +            film = null;
тут возвращается   id (так как сейчас это присваевает сама БД) когда включим UUID будет  void и я так понимаю проблема уйдет. Сейчас добавила комент в код

2022-11-27 20:20 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDao.java
> +    int insertFilm(Film film);
тут возвращается id (так как сейчас это присваевает сама БД) когда включим UUID будет void и я так понимаю проблема уйдет. Сейчас добавила комент в код

2022-11-27 20:30 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +        String sql = "SELECT id, name, description, release_date, duration, rating_MPA FROM film WHERE id = ?";
если параметры это - фильтры селекта (id, name, description, release_date, duration, rating_MPA - то не знала что их тоже можно и нужно делать вопросами (?) мы же в них не подставляем значения ( значит скл иньекции быть не может)
а id = ?  итак с ввопросом (?)

прошу уточнить что имелось ввиду

2022-11-28 07:59 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +    private NamedParameterJdbcTemplate namedDb;
Можно было просто Join`ить таблицы, но в целом обсудили в Slack, что допустим и такой вариант

2022-11-28 10:24 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +                .releaseDate(resultSet.getDate("release_date").toLocalDate())
может) упустила этот момент

2022-11-28 10:26 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmGenreDaoImpl.java
> +    private final JdbcTemplate db;
исправила

2022-11-28 10:26 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/user/AddUserRequest.java
> +package ru.yandex.practicum.filmorate.web.dto.user;
Делала по примеру с вебинара с наставником

2022-11-28 10:32 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/Id.java
> +public class Id {
Использую для ДТО

в коде  описала:
`@Data
public class AddFilmRequest {
    @NotBlank(message = "'name' should non be empty")
    private String name;
    @Size(max = 200, message = "'description' should have length no more than 200")
    private String description;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonDeserialize(using = LocalDateDeserializer.class)
    @JsonSerialize(using = LocalDateSerializer.class)
    @ReleaseDate
    private LocalDate releaseDate;
    @Positive
    private int duration;
    private List<Id> genres;
    @NotNull(message = "'mpa' must not be null")
    @JsonProperty("mpa")
    private Id ratingMpaId;
}`


Тело запроса на создание фильма

`POST /films

{
  "name": "New film",
  "releaseDate": "1999-04-30",
  "description": "New film about friends",
  "duration": 120,
  "rate": 4,
  "mpa": { "id": 3},
  "genres": [{ "id": 1}]
}`

2022-11-28 10:34 UTC, AlexandraKozhevnikova commented on src/main/java/ru/yandex/practicum/filmorate/web/dto/Id.java
> +public class Id {
а как иначе на джаве описать объект, который в джейсон представлен как { "id": 3}?

2022-11-28 10:49 UTC, AlexandraKozhevnikova commented on src/test/java/ru/yandex/practicum/filmorate/ImMemoryFilmStorageTest.java
> +    public void updateFilmTest() {
исправила метод    update для фильмов (был правильно написан только для юзеров)
спасибо)

конкретно в этом классе Исключение не получить, так как он на инмемори

на исключение при обновлении несуществующего элемента, есть тест только для ветки с Юзером (решила разбить что фильмы на сторадже проверяю а юзеров на сервисе для инмемори, так как ну очень огромное задание, не хочется добавлять копипасту на другую сущность)
```
 @Test
    public void updateNotExistUserTest() {
        User user = User.builder()
                .id(123)
                .login("pinki")
                .email("pinki@ya.ru")
                .birthday(LocalDate.now())
                .build();

        Assertions.assertThrows(
                NoSuchElementException.class,
                () -> service.update(user)
        );
    }

2022-11-28 13:46 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/db/dao/FilmDaoImpL.java
> +        String sql = "SELECT id, name, description, release_date, duration, rating_MPA FROM film WHERE id = ?";
Я имел ввиду, почему не сделать как и в других местах вы делали:
SELECT * FROM film WHERE ....

2022-11-28 13:46 UTC, Frilock approved these changes
Принято

2022-11-28 21:46 UTC, merged